[features]
seeds = false
skip-lint = false
[programs.devnet]
testing = "BVqsAZ8qSWK7TiF88WnyVnjKX83H3Ehz6Py5hNm8ReVJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/yusuf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
